@baseUrl = http://localhost:5141/api/platforms

@apiKey = <your-generated-api-key-here>

GET {{baseUrl}}?pageIndex=1&pageSize=10
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}?pageIndex=1&pageSize=10&search=Xbox
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}?pageIndex=1&pageSize=10&sortBy=platformname&descending=true
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}/1
x-api-key: {{apiKey}}
Accept: application/json

###

POST {{baseUrl}}
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "platformName": "Xbox"
}

###

PUT {{baseUrl}}/1
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "platformName": "Xbox 2"
}

###

DELETE {{baseUrl}}/1
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}/1/commands?pageIndex=1&pageSize=10
x-api-key: {{apiKey}}
Accept: application/json

###

