@baseUrl = http://localhost:5141/api/platforms

GET {{baseUrl}}?pageIndex=1&pageSize=10
Accept: application/json

###

GET {{baseUrl}}?pageIndex=1&pageSize=10&search=Xbox
Accept: application/json

###

GET {{baseUrl}}?pageIndex=1&pageSize=10&sortBy=platformname&descending=true
Accept: application/json

###

GET {{baseUrl}}/1
Accept: application/json

###

POST {{baseUrl}}
Content-Type: application/json

{
    "platformName": "Xbox"
}

###

PUT {{baseUrl}}/1
Content-Type: application/json

{
    "platformName": "Xbox 2"
}

###

DELETE {{baseUrl}}/1
Accept: application/json

###

GET {{baseUrl}}/1/commands
Accept: application/json

###

