@baseUrl = http://localhost:5141/api/commands

@apiKey = <your-generated-api-key-here>

GET {{baseUrl}}?pageIndex=1&pageSize=10
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}?pageIndex=1&pageSize=10&search=dotnet
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}?pageIndex=1&pageSize=10&sortBy=howto&descending=true
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}/1
x-api-key: {{apiKey}}
Accept: application/json


###

POST {{baseUrl}}
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "platformId": 1,
    "howTo": "How to create a new project",
    "commandLine": "dotnet new console -o MyProject"
}

###

PUT {{baseUrl}}/1
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "platformId": 1,
    "howTo": "How to create a new project.",
    "commandLine": "dotnet new console -o MyProject"
}

###

DELETE {{baseUrl}}/1
x-api-key: {{apiKey}}
Accept: application/json

###

GET {{baseUrl}}/platform/1?pageIndex=1&pageSize=10
x-api-key: {{apiKey}}
Accept: application/json

###


