// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using commander.infrastructure.Persistence;

#nullable disable

namespace commander.infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260429141635_AddKeyRegistrations")]
partial class AddKeyRegistrations
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("commander.domain.Entities.Command", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("CommandLine")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("HowTo")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("PlatformId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("PlatformId")
                    .HasDatabaseName("Index_Command_PlatformId");

                b.ToTable("Commands");
            });

        modelBuilder.Entity("commander.domain.Entities.KeyRegistration", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("character varying(250)");

                b.Property<string>("KeyHash")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<Guid>("KeyIndex")
                    .HasColumnType("uuid");

                b.Property<Guid>("Salt")
                    .HasColumnType("uuid");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.HasIndex("KeyIndex")
                    .IsUnique()
                    .HasDatabaseName("Index_KeyRegistration_KeyIndex");

                b.ToTable("KeyRegistrations");
            });

        modelBuilder.Entity("commander.domain.Entities.Platform", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PlatformName")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Platforms");
            });

        modelBuilder.Entity("commander.domain.Entities.Command", b =>
            {
                b.HasOne("commander.domain.Entities.Platform", "Platform")
                    .WithMany("Commands")
                    .HasForeignKey("PlatformId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Platform");
            });

        modelBuilder.Entity("commander.domain.Entities.Platform", b =>
            {
                b.Navigation("Commands");
            });
#pragma warning restore 612, 618
    }
}
